"""
Autonomous Task Executor — Multi-step workflow execution engine.
Executes AI-generated workflow plans with parallel step groups.
"""
import subprocess
import threading
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Callable, Optional
from aios.app_launcher import launch_apps_parallel, _launch_single_app
from aios.context_memory import memory

# Shared executor — created once, reused for every parallel group.
# Using 8 workers matches the parallel app-launch pool size and covers
# typical 2–4 app launch + command patterns comfortably.
_EXECUTOR = ThreadPoolExecutor(max_workers=8, thread_name_prefix="aios-task")


class StepResult:
    def __init__(self, step_id: int, action: str, target: str, status: str, output: str = "", error: str = ""):
        self.step_id = step_id
        self.action = action
        self.target = target
        self.status = status  # success | failed | skipped
        self.output = output
        self.error = error
        self.time_ms = 0

    def to_dict(self):
        return {
            "step_id": self.step_id,
            "action": self.action,
            "target": self.target,
            "status": self.status,
            "output": self.output,
            "error": self.error,
            "time_ms": self.time_ms,
        }


def _execute_step(step: dict) -> StepResult:
    """Execute a single workflow step."""
    action = step.get("action", "")
    target = step.get("target", "")
    step_id = step.get("step_id", 0)
    t_start = time.time()

    result = StepResult(step_id, action, target, "unknown")

    try:
        if action == "open_app":
            res = _launch_single_app(target)
            result.status = "success" if "launched" in res["status"] else "failed"
            result.output = f"PID: {res.get('pid', 'N/A')}"
            result.error = res.get("error", "")
            memory.log_app_opened(target)

        elif action == "run_command":
            proc = subprocess.run(
                target, shell=True, capture_output=True, text=True, timeout=30
            )
            result.status = "success" if proc.returncode == 0 else "failed"
            result.output = proc.stdout[:200]
            result.error = proc.stderr[:200]
            memory.log_command(target, result.output)

        elif action == "file_search":
            from aios.file_manager import smart_search
            files = smart_search(target, max_results=5)
            result.status = "success"
            result.output = "\n".join(f["path"] for f in files[:3])

        elif action == "wait":
            secs = float(target) if target.replace(".", "").isdigit() else 1.0
            time.sleep(secs)
            result.status = "success"
            result.output = f"Waited {secs}s"

        elif action == "notify":
            result.status = "success"
            result.output = target

        else:
            result.status = "skipped"
            result.output = f"Unknown action: {action}"

    except subprocess.TimeoutExpired:
        result.status = "failed"
        result.error = "Command timed out after 30s"
    except Exception as e:
        result.status = "failed"
        result.error = str(e)

    result.time_ms = round((time.time() - t_start) * 1000)
    return result


class WorkflowExecutor:
    """
    Executes workflow plans generated by the LLM.
    Supports parallel step groups and progress callbacks.
    """

    def __init__(self, progress_callback: Callable = None):
        self.progress_callback = progress_callback or (lambda msg: None)

    def execute(self, workflow: dict) -> dict:
        """
        Execute a workflow plan dict.
        Steps with the same parallel_group run concurrently.
        parallel_group=0 means sequential.
        """
        steps = workflow.get("steps", [])
        workflow_name = workflow.get("workflow_name", "unnamed")

        if not steps:
            self.progress_callback(f"[AIOS] Workflow '{workflow_name}' has no steps to execute.")
            return {
                "workflow_name": workflow_name,
                "total_steps": 0,
                "success_count": 0,
                "fail_count": 0,
                "total_time_ms": 0,
                "results": [],
                "error": workflow.get("_raw", "Workflow has no steps"),
            }
        
        self.progress_callback(f"\n[AIOS] Executing workflow: {workflow_name}")
        self.progress_callback(f"[AIOS] {len(steps)} steps planned\n")

        all_results = []
        t_start = time.time()

        # Group steps by parallel_group
        groups = {}
        for step in steps:
            pg = step.get("parallel_group", 0)
            groups.setdefault(pg, []).append(step)

        # Execute group 0 steps sequentially, others in parallel within group
        for group_id in sorted(groups.keys()):
            group_steps = groups[group_id]
            
            if group_id == 0 or len(group_steps) == 1:
                # Sequential
                for step in group_steps:
                    self.progress_callback(
                        f"  → [{step.get('step_id')}] {step.get('description', step.get('target'))}"
                    )
                    result = _execute_step(step)
                    all_results.append(result)
                    status_icon = "✓" if result.status == "success" else "✗"
                    self.progress_callback(f"    {status_icon} {result.status} ({result.time_ms}ms)")
            else:
                # Parallel group — use the shared executor
                self.progress_callback(f"  ⚡ Parallel group {group_id}: {len(group_steps)} steps simultaneously")
                futures = {_EXECUTOR.submit(_execute_step, s): s for s in group_steps}
                for future in as_completed(futures):
                    step = futures[future]
                    result = future.result()
                    all_results.append(result)
                    status_icon = "✓" if result.status == "success" else "✗"
                    self.progress_callback(
                        f"    {status_icon} [{result.step_id}] {step.get('description', result.target)} "
                        f"({result.time_ms}ms)"
                    )

        total_time = round((time.time() - t_start) * 1000)
        success_count = sum(1 for r in all_results if r.status == "success")

        # Save workflow to memory
        memory.save_workflow(workflow_name, workflow)
        memory.increment_workflow_run(workflow_name)

        summary = {
            "workflow_name": workflow_name,
            "total_steps": len(steps),
            "success_count": success_count,
            "fail_count": len(all_results) - success_count,
            "total_time_ms": total_time,
            "results": [r.to_dict() for r in all_results],
        }

        self.progress_callback(
            f"\n[AIOS] Workflow complete: {success_count}/{len(all_results)} steps succeeded "
            f"in {total_time}ms"
        )
        return summary
